checks:
  javascript: true

build:
  nodes:
    coverage:
      tests:
        override:
          - command: ./run-my-tests
            coverage:
              file: coverage/coverage.xml   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
