language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

env:
    - JWT_SECRET="sOINnmjDDDxPPMkboC6YBU7etSTGUgYBOQMPS46R8cHNOuWrFfDGZsTtXhkdiNLU"


git:
    submodules: false

before_script:
    - npm install


services:
    - sqlite3

before_install:
    - sqlite3 db/test.sqlite < db/migrate.sql

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
